#!/bin/bash

# Initialize variables
store=".trader_runner"
env_file_path="$store/.env"
rpc_path="$store/rpc.txt"
operator_keys_file="$store/operator_keys.json"
operator_pkey_path="$store/operator_pkey.txt"
keys_json="keys.json"
keys_json_path="$store/$keys_json"
agent_pkey_path="$store/agent_pkey.txt"
agent_address_path="$store/agent_address.txt"
service_id_path="$store/service_id.txt"
service_safe_address_path="$store/service_safe_address.txt"
use_password=false
password_argument=""

# Set up Python command
if command -v python3 >/dev/null 2>&1; then
    PYTHON_CMD="python3"
elif command -v python >/dev/null 2>&1; then
    PYTHON_CMD="python"
else
    echo >&2 "Python is not installed!"
    exit 1
fi

echo ""
echo "-----------------"
echo " Service Registration "
echo "-----------------"
echo ""

# Create store directory if it doesn't exist
mkdir -p "$store"

# Helper functions
get_address() {
    local keys_json_path="$1"
    address=$($PYTHON_CMD -c 'import json; print(json.load(open("'"$keys_json_path"'"))[0]["address"])')
    echo -n "$address"
}

get_private_key() {
    local keys_json_path="$1"
    private_key=$($PYTHON_CMD -c 'import json; print(json.load(open("'"$keys_json_path"'"))[0]["private_key"])')
    private_key="${private_key#0x}"
    echo -n "$private_key"
}

# Prompt for RPC
echo "Enter Gnosis RPC"
echo "--------------"
read -rsp "Enter a Gnosis RPC that supports eth_newFilter [hidden input]: " rpc 
echo ""

# Check the RPC
echo "Checking the provided RPC: $rpc..."

rcp_response=$(curl -s -S -X POST \
    -H "Content-Type: application/json" \
    --data '{"jsonrpc":"2.0","method":"eth_newFilter","params":["invalid"],"id":1}' "$rpc")

rcp_error_message=$(echo "$rcp_response" | \
$PYTHON_CMD -c "import sys, json;
try: print(json.load(sys.stdin)['error']['message'])
except Exception as e: print('Exception processing RCP response')")

rcp_exception=$([[ "$rcp_error_message" == "Exception processing RCP response" ]] && echo true || echo false)
if [ "$rcp_exception" = true ]; then
    echo "Error: The received RCP response is malformed. Please verify the RPC address."
    echo "Terminating script."
    exit 1
fi

rcp_out_of_requests=$([[ "$rcp_error_message" == "Out of requests" ]] && echo true || echo false)
if [ "$rcp_out_of_requests" = true ]; then
    echo "Error: The provided RCP is out of requests."
    echo "Terminating script."
    exit 1
fi

rcp_new_filter_supported=$([[ "$rcp_error_message" == "The method eth_newFilter does not exist/is not available" ]] && echo false || echo true)
if [ "$rcp_new_filter_supported" = false ]; then
    echo "Error: The provided RPC does not support 'eth_newFilter'."
    echo "Terminating script."
    exit 1
fi

echo "RPC checks passed."
echo ""

# Store RPC
echo -n "$rpc" > "$rpc_path"

# Prompt for Subgraph API key
echo "Provide a Subgraph API key"
echo "--------------------------"
echo "You need a Subgraph API key that can be obtained at The Graph https://thegraph.com/studio/apikeys/"
echo ""
read -rsp "Please, enter a Subgraph API key [hidden input]: " SUBGRAPH_API_KEY
echo ""

while [ -z "${SUBGRAPH_API_KEY}" ]; do
    echo "You cannot enter a blank API key."
    read -rsp "Please, enter a Subgraph API key [hidden input]: " SUBGRAPH_API_KEY
    echo ""
done

# Store Subgraph API key in .env
echo "SUBGRAPH_API_KEY=$SUBGRAPH_API_KEY" > "$env_file_path"

cd trader

# Generate keys
echo "Generating operator and agent keys..."

# Generate operator keys
poetry run autonomy generate-key -n1 ethereum
mv "$keys_json" "../$operator_keys_file"
operator_address=$(get_address "../$operator_keys_file")
operator_pkey=$(get_private_key "../$operator_keys_file")
echo -n "$operator_pkey" > "../$operator_pkey_path"
echo "Your operator's autogenerated public address: $operator_address"

# Generate agent keys
poetry run autonomy generate-key -n1 ethereum
mv "$keys_json" "../$keys_json_path"
agent_address=$(get_address "../$keys_json_path")
agent_pkey=$(get_private_key "../$keys_json_path")
echo -n "$agent_pkey" > "../$agent_pkey_path"
echo -n "$agent_address" > "../$agent_address_path"
echo "Your agent instance's autogenerated public address: $agent_address"
echo ""

# Export necessary environment variables
export CUSTOM_CHAIN_RPC="$rpc"
export CUSTOM_CHAIN_ID=100
export RPC_RETRIES=40
export RPC_TIMEOUT_SECONDS=120
export ATTENDED=false

# Define service interaction functions
get_on_chain_service_state() {
    local service_id="$1"
    local service_info=$(poetry run autonomy service --use-custom-chain info "$service_id")
    local state="$(echo "$service_info" | awk '/Service State/ {sub(/\|[ \t]*Service State[ \t]*\|[ \t]*/, ""); sub(/[ \t]*\|[ \t]*/, ""); print}')"
    echo "$state"
}

ensure_rpc_reports_service_state() {
    local service_id="$1"
    local expected_state="$2"
    local timeout=60
    local start_time=$(date +%s)
    local current_state="$(get_on_chain_service_state "$service_id")"
    
    echo -n "Waiting for service $service_id to reach $expected_state state..."
    
    while [ "$current_state" != "$expected_state" ]; do
        echo -n "."
        sleep 5
        current_state="$(get_on_chain_service_state "$service_id")"
        
        if [ $(($(date +%s) - start_time)) -ge $timeout ]; then
            echo " Timeout!"
            return 1
        fi
    done
    echo " Done!"
    echo ""
}

# Select staking program if not already set
if [ -z "${STAKING_PROGRAM}" ]; then
    echo "Setting up staking program..."
    poetry run python "../scripts/choose_staking.py"
    source "$env_file_path"
fi

# Mint new service if needed
if [ ! -f "$service_id_path" ]; then
    echo "Minting new service..."
    nft="bafybeig64atqaladigoc3ds4arltdu63wkdrk3gesjfvnfdmz35amv7faq"
    service_id=$(poetry run autonomy mint \
        --retries $RPC_RETRIES \
        --timeout $RPC_TIMEOUT_SECONDS \
        --use-custom-chain \
        service packages/valory/services/trader/ \
        --key "../$operator_pkey_path" \
        --nft $nft \
        -a $AGENT_ID \
        -n 1 \
        --threshold 1)
    
    # Extract service ID from response
    service_id="${service_id##*: }"
    if ! [[ "$service_id" =~ ^[0-9]+$ || "$service_id" =~ ^[-][0-9]+$ ]]; then
        echo "Service minting failed: $service_id"
        exit 1
    fi
    echo -n "$service_id" > "../$service_id_path"
    export ON_CHAIN_SERVICE_ID="$service_id"
fi

# Get current service state
service_state="$(get_on_chain_service_state "$service_id")"
echo "Current service state: $service_state"
echo ""

# Handle each state transition
if [ "$service_state" = "PRE_REGISTRATION" ]; then
    echo "Activating service registration..."
    poetry run autonomy service --use-custom-chain activate "$service_id" --key "../$operator_pkey_path"
    ensure_rpc_reports_service_state "$service_id" "ACTIVE_REGISTRATION"
    service_state="ACTIVE_REGISTRATION"
fi

if [ "$service_state" = "ACTIVE_REGISTRATION" ]; then
    echo "Registering agent instance..."
    poetry run autonomy service --use-custom-chain register "$service_id" -a "$AGENT_ID" -i "$agent_address" --key "../$operator_pkey_path"
    ensure_rpc_reports_service_state "$service_id" "FINISHED_REGISTRATION"
    service_state="FINISHED_REGISTRATION"
fi

if [ "$service_state" = "FINISHED_REGISTRATION" ]; then
    echo "Deploying service..."
    poetry run autonomy service --use-custom-chain deploy "$service_id" --key "../$operator_pkey_path"
    ensure_rpc_reports_service_state "$service_id" "DEPLOYED"
    service_state="DEPLOYED"
fi

# Get and store Safe address if service is deployed
if [ "$service_state" = "DEPLOYED" ]; then
    echo "Getting Safe address..."
    service_info=$(poetry run autonomy service --use-custom-chain info "$service_id")
    safe=$(echo "$service_info" | grep "Multisig Address")
    safe=$(echo "$safe" | awk '{ print substr( $0, 31, length($0) - 33 ) }')
    echo -n "$safe" > "../$service_safe_address_path"
    echo "Safe address: $safe"
    echo ""
    
    echo "Service successfully registered and deployed!"
    echo "You can now run quick_stake.sh to stake the service."
else
    echo "Failed to reach DEPLOYED state. Current state: $service_state"
    exit 1
fi